#!/bin/bash

# Add colours where possible
# For the ls command: -h for human readable file sizes (if used), -N for literal file names without quotes
alias \
    ls="ls -hN --color=auto --group-directories-first" \
	  grep="grep --color=auto" \
	  diff="diff --color=auto"

# Abbreviate common commands
alias \
	  reboot="sudo reboot" \
	  sleep="systemctl suspend-then-hibernate" \
	  shutdown="shutdown now" \
    hibernate="systemctl hibernate" \
    hybrid-sleep="systemctl hybrid-sleep" \
    brightness="sudo brightnessctl" \
	  nay="paru -Rns" \
    naru="paru -Rns"
    yargo="rustup update ; cargo install-update -a" \
    nord="nordvpn" \
	  reload-zshrc="source $ZDOTDIR/.zshrc" \
    night_mode="pgrep redshift >/dev/null 2>&1 || { redshift >/dev/null 2>&1 & disown ; }" \
    R="sudo R --quiet"

# QoL binds
alias \
	  update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg" \
    update-mirrors="sudo reflector --protocol https --country 'United Kingdom' --latest 200 --age 24 --sort rate --save /etc/pacman.d/mirrorlist" \
	  what-broke="sudo journalctl -b -1 -p 3" \
	  figlet="figlet -t" \
	  ix=$'curl -F \'f:1=<-\' ix.io' \
	  copy-to-clipboard="xclip -selection clipboard" \
	  matrix="cmatrix -b -u 10" \
	  zathura="zathura --fork" \
    window-name="xprop | grep -E '^WM_((CLASS)|(NAME))'"

# Replacement programs that you know by another name
command -v ytop >/dev/null && alias gotop="ytop"
command -v yay  >/dev/null && alias yay="paru"

