#!/bin/sh

# Requires acpi
# Get battery % and whether it was charging or not
# Returns in the for +/-num e.g. -79 for discharging from 79%

for battery in /sys/class/power_supply/BAT? ; do
	status=$(sed "s/Charging/\+/;s/Not charging/-/;s/Discharging/-/;s/Unknown/\?/" "$battery"/status)
	charge=$(cat "$battery"/capacity)
	echo "$status$charge"
done

