#!/bin/sh

# Requires acpi
# Get battery % and whether it was charging or not
# Returns in the for +/-num e.g. -79 for discharging from 79%

# echo $(acpi -b | awk -F '[,:%]' '{print ($2 == "Charging" ? "+" : "-") $3}')
echo $(acpi -b | grep -Eo '(Disc|C)harging, [0-9]{1,3}' | sed -e 's/Discharging, /-/' -e 's/Charging, /\+/')
