#!/bin/sh

# Compile markdown-esque documents
# Bound in nvim
# Totally not stolen from Luke Smith

# .ms - Groff. Use refer then pre-prossess with preconv, eqn, pic, tbl. Save as PDF
# .rmd - R markdown.

file=$(readlink -f "$1")
dir=$(dirname "$file")
base="${file%.*}"

cd "$dir" || exit

case "$file" in
	*\.ms) refer - PS -e "$file" | groff -me -ms -kept -T pdf > "$base",pdf ;;
	*\.[rR]md) Rscript -e "require(rmarkdown); rmarkdown::render('$file', quiet=TRUE)" ;;
esac
