#!/bin/sh

# Provide USE_SUDO=true as an environment variable to run as sudo

run_command="{cmd}"

[ "$USE_SUDO" = true ] && run_command="sudo -A {cmd}"

rofi -no-lazy-grab -show drun -theme themes/column_launcher.rasi -run-command "$run_command" -cache-dir "$HOME/.cache/rofi"

